; default theme, also embedded in the source of fast-syntax-highlighting
[base]
default          = none
unknown-token    = white
commandseparator = none
redirection      = none
here-string-tri  = #f9e2af
here-string-text = 18
here-string-var  = #89dceb,bg:18
exec-descriptor  = #fab387,bold
comment          = #6c7086
correct-subtle   = #a6e3a1
incorrect-subtle = white
subtle-separator = #a6e3a1
subtle-bg        = bg:18
secondary        = free
[command-point]
reserved-word     = #cba6f7
subcommand        = #cba6f7
alias             = white
suffix-alias      = white
global-alias      = white
builtin           = white
function          = white
command           = white
precommand        = white
hashed-command    = white
single-sq-bracket = #fab387
double-sq-bracket = #fab387
double-paren      = #cba6f7
[paths]
path          = #89b4fa
pathseparator =
path-to-dir   = #89b4fa,underline
globbing      = #cba6f7,bold
globbing-ext  = #cba6f7
[brackets]
paired-bracket  = bg:#313244
bracket-level-1 = #a6e3a1,bold
bracket-level-2 = #f9e2af,bold
bracket-level-3 = #89dceb,bold
[arguments]
single-hyphen-option   = #fab387
double-hyphen-option   = #fab387
back-quoted-argument   = #cba6f7
single-quoted-argument = #a6e3a1
double-quoted-argument = #a6e3a1
dollar-quoted-argument = #a6e3a1
[in-string]
back-dollar-quoted-argument           = #89dceb
back-or-dollar-double-quoted-argument = #89dceb
[other]
variable             = #cba6f7
assign               = none
assign-array-bracket = #a6e3a1
history-expansion    = #89b4fa,bold
[math]
mathvar = #cba6f7,bold
mathnum = #fab387
matherr = #f38ba8
[for-loop]
forvar = none
fornum = #fab387
foroper = #f9e2af
forsep  = #f9e2af,bold
[case]
case-input       = #89dceb
case-parentheses = #f9e2af
case-condition   = bg:#313244
