splash = false

wallpaper {
    monitor = DP-5
    path = /home/wiki/.config/hypr/wallpapers/soft-rose.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-4
    path = /home/wiki/.config/hypr/wallpapers/soft-rose.jpg
    fit_mode = cover
}
