--ozone-platform-hint=auto
--enable-features=UseOzonePlatform,WaylandLinuxDrmSyncobj
--force-device-scale-factor=1
--enable-accelerated-video-decode
--enable-features=AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoDecodeLinuxGL,VaapiIgnoreDriverChecks,VaapiOnNvidiaGPUs
